from .slowprint import slowprint_a, slowprint_text, slowprint_1
from rich.console import Console
import time
import os

title_console = Console(color_system="windows")
start_console = Console(color_system="windows")
text_console = Console(color_system="windows")
choose_console = Console(color_system="windows")

def Page2():
    os.system("clear")
    text_console.print("公司", justify="center")
    time.sleep(3)
    os.system("clear")
    slowprint_text("""
小生物来到了一处公司。
据说这里是人类用劳动力换取报酬的地方，这对小生物而言是一个全新的概念。
想要用劳动力换取报酬的前提条件，则是参加一种名为“面试”的东西。
今天，这家名为“男酮工作室”的公司正在展开一场面试。
好奇的小生物溜进去时，正好是面试的中途。""")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("你以为你接受的是谁的爱？是我的爱！")
    slowprint_text("""
坐在面试官位置的少女似乎正对面试者大发雷霆。
""")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("我的爱！我的如此珍贵的爱！")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("你竟敢拒绝我的爱！")
    print()
    slowprint_text("办公室的其他员工窃窃私语。")
    text_console.print("[yellow]（员工）游魂[/]：", end="")
    time.sleep(1)
    slowprint_text("我又漏看了两集？冰蓝这是怎么了？")
    text_console.print("[yellow]（员工）桶鸟[/]：", end="")
    time.sleep(1)
    slowprint_text("我不知道啊，昨天她不是和老G一起约会去了吗？照理说约会之后心情不应该非常好吗？")
    text_console.print("[yellow]（员工）027[/]：", end="")
    time.sleep(1)
    slowprint_text("嘘——你忘啦？上次冰蓝妹妹背着gamer给我偷偷发消息的事情？就是那个“027，gamer不在，人家想你啦><”那个！")
    text_console.print("[yellow]（员工）猫店长[/]：", end="")
    time.sleep(1)
    slowprint_text("这么说是有这么一回事，G先生该不会...")
    text_console.print("[yellow]（员工）雨林：", end="")
    time.sleep(1)
    slowprint_text("唔这么说gamer桑不太好吧...")
    text_console.print("[yellow]（员工）殷红[/]：", end="")
    time.sleep(1)
    slowprint_text("哎呀兄弟们，这个我觉得还是得再看看再看看。总之先吃瓜——")
    slowprint_text("""
这些精确控制音量的八卦猜测并没有传到当事人的耳朵里，冰蓝只是气呼呼地瞪着面前的人。
坐立不安的江江却听到了大家的讨论，有些尴尬地扭了扭脖子。
""")
    text_console.print("[cyan]江江[/]：", end="")
    time.sleep(1)
    slowprint_text("那个...")
    slowprint_text("""江江才张嘴，就换来对方的狠狠一瞪。
他吞吞口水，艰难地说出了下半句话。""")
    text_console.print("[cyan]江江[/]：", end="")
    time.sleep(1)
    slowprint_text("我，那个，对不起，你，你是个好人。")
    slowprint_text("""听了这句话，对面的火气更大了。。""")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("为什么！！！你为什么要拒绝我的爱！")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("没有人，没有人可以拒绝我的爱！")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("只要你点点头接受了我，你现在就可以入职！")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("不用再去参加任何的面试，不用再担心被开除。")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("不用再担心像那个新闻里的45岁阿姨一样因为失业只能住桥洞里了。")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("不用捡瓶盖，不用睡纸板箱，更不用担心半夜涨潮被河水冲走。")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("你只需要接受我，然后在这份劳动合同上签名。")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("然后每天工作18小时每周工作7天就可以了！")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("还有经常的加班能够让你实现个人价值！这不是非常棒的条件吗！")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_text("江江！把你余生的剩余价值交给我吧！")
    slowprint_text("说到激动处，冰蓝向对方伸出手，却被对方歪头躲过。")
    text_console.print("[cyan]江江[/]：", end="")
    time.sleep(1)
    slowprint_text("不好意西我想起来还有三十分钟我最爱的节目假面来不打就要播了我先走了——")
    slowprint_text("""江江宛如脱缰的菜狗一般冲出了办公室，只余下一片寂静。
孤独的冰蓝呆呆矗立在办公室的中央，还维持着手臂前伸的姿势。""")
    text_console.print("[cyan]冰蓝[/]：", end="")
    time.sleep(1)
    slowprint_a("...")
    text_console.print("[yellow]（员工）桶鸟[/]：", end="")
    time.sleep(1)
    slowprint_text("冰蓝酱好像有点可怜啊，昨天才被老G那样对待今天又失恋了。")
    text_console.print("[yellow]（员工）露鸢[/]：", end="")
    time.sleep(1)
    slowprint_text("比起可怜她，我想先问一下我们能挂她吗？")
    text_console.print("[yellow]（员工）殷红[/]：", end="")
    time.sleep(1)
    slowprint_text("我也觉得该挂啊兄弟们。")
    text_console.print("[yellow]（员工）猫店长[/]：", end="")
    time.sleep(1)
    slowprint_text("不太好吧，好歹过两天再挂。和G先生挂一起岂不是更好。")
    time.sleep(3)
    slowprint_1("......")
    time.sleep(1.5)
    print("""
    
""")
    text_console.print("此时小生物应该...？", justify="center")
    print()
    time.sleep(0.5)
    choose_console.print("1. [cyan]安慰冰蓝[/cyan]", justify="center")
    choose_console.print("2. [green]和员工一起挂冰蓝[/green]", justify="center")
    print()
    time.sleep(1)
    global choose3
    choose3 = int(choose_console.input("[yellow]你的选择是：[/]"))
    if choose3 == 1:
        os.system("clear")
        slowprint_text("""
即便是邪恶的资本家，也拥有追求爱情的权力。
即使是罪恶的资本家，在感到悲伤时也应被温柔以待
""")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("谢谢你，你真是个温柔的好人。")
        time.sleep(3)
        print()
        slowprint_text("【获得道具：冰蓝的好人卡*1】")
        time.sleep(1.5)
        print()
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("但总是沉溺于悲伤的情感可不行，得抬头往前走。我现在必须得寻找我的下一个打工人了。")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("说起来，你现在有工作吗？")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("要是没有工作，有兴趣来我们这里打工吗？")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("只要做7休0，每天只用上班18小时就可以了。")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("是非常有竞争力的工作时间呢，还有经常的加班让你的能力得到更好的锻炼。")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("如何？很宽厚的条件吧？")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("今天签合同还送不锈钢大铁盆和牙刷牙杯，以后在公司打地铺加班的时候就更方便了。")
        slowprint_text("""
收到邀请的小生物大受感动。
离开公司时，它暗自发誓，要成为一个能够充满打工之力的人""")
    elif choose3 == 2:
        os.system("clear")
        slowprint_text("""
正义理应得到伸张。
被压迫的打工人们渴望自由，渴望处刑为他们带来痛苦的源头。
员工们纷纷向小生物叙述自己曾经遭遇过的被压迫故事，让小生物听得眼泪汪汪。
小生物决心加入他们。
""")
        time.sleep(3)
        print()
        slowprint_text("【获得道具：打工群友的认可*1】")
        time.sleep(1.5)
        print()
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("你们，你们这是要做什么？！")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("我给了你们工作，你们难道不应该感恩吗？")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("觉得工资不够花，你们不会一天干25小时，一周干8天吗？")
        text_console.print("[cyan]冰蓝[/]：", end="")
        time.sleep(1)
        slowprint_text("快停下，没了我，你们连工作都没有——")
        slowprint_text("""
收到邀请的小生物大受感动。
离开公司时，它暗自发誓，要成为一个能够守护打工人的人""")